### ISSUE TITLE
refactor npinit

### ISSUE THREAD

**Issue by akileez** [akileez/issues#4]
project: [npinit](https://github.com/akileez/npinit)
- [x] use process.nextTick for callbacks (https://github.com/akileez/npinit/issues/54)
- [x] use logger in place of process.stdout.write (https://github.com/akileez/npinit/issues/52)
- [x] allow github repo to be initiated after initial run of npinit (https://github.com/akileez/npinit/issues/45)

**Comment by akileez** [comment]
test npinit and npm-install-modules for a large amount of files. test using series.each.

**Comment by akileez** [comment]
closing in lieu of [https://github.com/akileez/npinit/issues/59]
all issues here have been solved.
